//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.5
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\chris gilbert\source\repos\Database\Database\SQLGrammar\SQLGrammar.g4 by ANTLR 4.6.5

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Database.Parsing {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="SQLGrammarParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.5")]
[System.CLSCompliant(false)]
public interface ISQLGrammarListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLGrammarParser.dmlstatements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDmlstatements([NotNull] SQLGrammarParser.DmlstatementsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLGrammarParser.dmlstatements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDmlstatements([NotNull] SQLGrammarParser.DmlstatementsContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLGrammarParser.select_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelect_statement([NotNull] SQLGrammarParser.Select_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLGrammarParser.select_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelect_statement([NotNull] SQLGrammarParser.Select_statementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLGrammarParser.column_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterColumn_list([NotNull] SQLGrammarParser.Column_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLGrammarParser.column_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitColumn_list([NotNull] SQLGrammarParser.Column_listContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLGrammarParser.column_element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterColumn_element([NotNull] SQLGrammarParser.Column_elementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLGrammarParser.column_element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitColumn_element([NotNull] SQLGrammarParser.Column_elementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLGrammarParser.column_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterColumn_name([NotNull] SQLGrammarParser.Column_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLGrammarParser.column_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitColumn_name([NotNull] SQLGrammarParser.Column_nameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="SQLGrammarParser.compileUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompileUnit([NotNull] SQLGrammarParser.CompileUnitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SQLGrammarParser.compileUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompileUnit([NotNull] SQLGrammarParser.CompileUnitContext context);
}
} // namespace Database.Parsing
